logicalclocks/hopsworks-chef

templates/default/tables.sql.erb
Including glassfish timer table, for job scheduling.
=> Include newest schema from Hopsworks develop branch.

recipes/letsencrypt.rb
I tried to simplify the script a little using consistent syntax and indentation. 
openssl as a package exists for RHEL and Debian and suits our needs. 
TODO 
Once the LetsEncrypt Cookbook is ready we should get rid of the last hard-coded variable.
=> some modifications

recipes/letsencrypt.rb
=> removed errorprone commands

Berksfile, attributes/default.rb, recipes/default.rb, templates/default/tables.sql.erb
Changes to make two factor optional
=> Fix 2 factor optional

templates/default/tables.sql.erb
Simplify jobs_history table constraints. Removed executions_input_files table.
=> Job history

templates/default/rows.sql.erb, templates/default/tables.sql.erb
=> added ops_log, meta_log, meta_data_schemaless tables

templates/default/rows.sql.erb, templates/default/tables.sql.erb
Add extra column to users table to store whether tours pop-up should be displayed or not
=> HOPSWORKS-16

templates/default/tables.sql.erb
add collate to hopsworks tables to fix foreign keys to hops
https://hopshadoop.atlassian.net/browse/HOPSWORKS-123
=> [HOPSWORKS-123]

attributes/default.rb, metadata.rb, recipes/default.rb, templates/default/deleteprojectcerts.sh.erb, templates/default/rows.sql.erb, templates/default/tables.sql.erb
One big commit to configure Hopsworks for RPC TLS
https://hopshadoop.atlassian.net/browse/HOPSWORKS-145
=> HOPSWORKS-145

attributes/default.rb, recipes/default.rb, templates/default/rows.sql.erb
* Add cuda to settings.java
* install hdfscontents
=> Jupyter fixes - cuda for jupyter, hdfscontents

recipes/default.rb, templates/default/rows.sql.erb
Merge at the same time as hopshadoop/hopsworks#620
=> [HOPSWORKS-165] add path to HDFS UI in hopsworks settings

templates/default/tables.sql.erb
Add extra column to store service certificates password
https://hopshadoop.atlassian.net/browse/HOPSWORKS-166
=> HOPSWORKS-166

templates/default/tables.sql.erb
Reverts hopshadoop/hopsworks-chef#81
=> Revert "HOPSWORKS-166"

templates/default/createusercerts.sh.erb
Change truststore password
https://hopshadoop.atlassian.net/browse/HOPSWORKS-169
=> HOPSWORKS-169

templates/default/createusercerts.sh.erb
Reverts hopshadoop/hopsworks-chef#83
=> Revert "HOPSWORKS-169"

Berksfile, recipes/install.rb, templates/default/jupyter.sh.erb, templates/default/rows.sql.erb
This is a bunch of fixes to get service-specific user/groups working again.
=> HOPSWORKS-175 - users/groups

templates/default/createusercerts.sh.erb, templates/default/tables.sql.erb
* HOPSWORKS-166
https://hopshadoop.atlassian.net/browse/HOPSWORKS-166
* HOPSWORKS-169
https://hopshadoop.atlassian.net/browse/HOPSWORKS-169
=> HOPSWORKS-166_169

templates/default/tables.sql.erb
Jira: https://hopshadoop.atlassian.net/browse/HOPSWORKS-184
Merge only in conjunction with: https://github.com/hopshadoop/hopsworks/pull/637
=>  [HOPSWORKS-184] Remove from DatasetService assumption datasets are under /Projects

templates/default/views.sql.erb
projects_management view is not needed anymore after hopsworks-181
https://hopshadoop.atlassian.net/browse/HOPSWORKS-187
=> [HOPSWORKS-187] Remove creation of projects_management view

LICENSE, recipes/install.rb, templates/default/jupyter-launch.sh.erb, templates/default/tables.sql.erb
Jupyter kernel enable/disable per project.
=> Pythonkernel - HOPSWORKS-189

recipes/default.rb, templates/default/rows.sql.erb, templates/default/tables.sql.erb
Fixing some bugs in conda as well.
=> HOPSWORKS-193 + jupyter metrics

templates/default/rows.sql.erb
Add a comma-separated list of user emails that should not be persisted in the database for auditing
=> HOPSWORKS-159

templates/default/tables.sql.erb
HOPSWORKS-273 Add field for number of MPI processes
This depends on the hopsworks-chef PR with the same name.
=> HOPSWORKS-273 Add field for number of MPI processes

templates/default/tables.sql.erb
Needed by hopshadoop/hopsworks#755
=> [HOPSWORKS-315] ,  [HOPSWORKS-316] 

attributes/default.rb, metadata.rb, recipes/install.rb
Add master encryption password file
It should be merged together with https://github.com/hopshadoop/hopsworks/pull/786
https://hopshadoop.atlassian.net/browse/HOPSWORKS-346
=> HOPSWORKS-346

templates/default/rows.sql.erb, templates/default/tables.sql.erb
=> HOPSWORKS-345

attributes/default.rb, metadata.rb, templates/default/rows.sql.erb, templates/default/tables.sql.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-401?filter=-1
=> HOPSWORKS-401

templates/default/dump_web_logs_to_hdfs.sh.erb
[fix_weblogs_dumper]  Remove file if already exists and change permissions to 0750
[fix_weblogs_dumper]  Fix exit codes
[fix_weblogs_dumper]  Change the regular expression for the log files
[fix_weblogs_dumper]  Refinements
[fix_weblogs_dumper]  Fix regex bug
=> [fix_weblogs_dumper]  Fix web logs dump script bugs

attributes/default.rb, recipes/default.rb, recipes/image.rb, recipes/install.rb, templates/default/glassfish_sudoers.erb, templates/default/jupyter.sh.erb, templates/default/tfserving-kill.sh.erb, templates/default/tfserving-launch.sh.erb, templates/default/tfserving-stop.sh.erb, templates/default/tfserving.sh.erb
=> Creating a VM Image 

recipes/install.rb, templates/default/tables.sql.erb, templates/default/tfserving-kill.sh.erb, templates/default/tfserving-launch.sh.erb, templates/default/tfserving.sh.erb
HOPSWORKS-265 TensorFlow Serving
=> HOPSWORKS-265 TensorFlow Serving

recipes/default.rb, templates/default/login.conf.erb
Needs a new cauthrealm jar, compiled from this branch https://github.com/hopshadoop/CauthRealm/tree/cleanup
=> fix for cauthRealm cleanup

recipes/default.rb, recipes/install.rb, templates/default/sql/0.0.2__initial_tables.sql.erb, templates/default/tfserving-kill.sh.erb, templates/default/tfserving-launch.sh.erb, templates/default/tfserving.sh.erb
Hopsworks 436 fixes for TF Serving
=> HOPSWORKS 436

templates/default/jupyter-launch.sh.erb, templates/default/jupyter.sh.erb
Export environment variable pointing to the secret materialization directory. This env var  will be picked up by HopsSSLSocketFactory to load the certificates.
It is linked with PR https://github.com/hopshadoop/hopsworks/pull/874
https://hopshadoop.atlassian.net/browse/HOPSWORKS-420
=> [HOPSWORKS-420]  Export environment variable for Jupyter

recipes/default.rb, templates/default/list_environment.sh.erb, templates/default/pipsearch.sh.erb, templates/default/sql/0.4.0.sql.erb, templates/default/sql/undo/0.4.0__undo.sql.erb
HOPSWORKS-412 pip-support and conda fixes
=> HOPSWORKS-412 pip-support and conda fixes

templates/default/sql/0.5.0.sql.erb, templates/default/sql/undo/0.5.0__undo.sql.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-460
=> [HOPSWORKS-460]  Add create table statement for system commands

attributes/default.rb, metadata.rb, templates/default/global-ca-sign-csr.sh.erb, templates/default/sql/0.5.0.sql.erb, templates/default/sql/undo/0.5.0__undo.sql.erb
[HOPSWORKS-454]  Add configuration for service certificates rotation interval
[HOPSWORKS-454]  Add argument for valid days
https://hopshadoop.atlassian.net/browse/HOPSWORKS-454
=> [HOPSWORKS-454]  Service certificate rotation

metadata.rb
https://github.com/hopshadoop/hops-testing/pull/54
=> [HOPSWORKS-477] Allow custom mirror configuration in conda

attributes/default.rb, metadata.rb, templates/default/sql/0.4.2.sql.erb, templates/default/sql/0.5.0.sql.erb, templates/default/sql/undo/0.4.2__undo.sql.erb
add sql for 0.4.2 and change job duplicate names
add 0.4.1 to versions
forgot to add sql files
add 0.4.2 to versions
=> HOPSWORKS-486

providers/certs.rb, recipes/default.rb, templates/default/deleteprojectcerts.sh.erb, templates/default/deleteusercerts.sh.erb
[HOPSWORKS-489]  Move certificate revocation to Hopsworks
[HOPSWORKS-489]  Allow following symlinks from docroot
[HOPSWORKS-489]  Generate CRL and symlink to Glassfish docroot
[HOPSWORKS-489]  Fix typo in intermediateCA CN
=> [HOPSWORKS-489] Revoke removed certificates

attributes/default.rb, metadata.rb, templates/default/sql/0.5.0.sql.erb, templates/default/sql/undo/0.5.0__undo.sql.erb
[HOPSWORKS-496]  Configure enable/disable of service certificate auto…matic rotation
=> [HOPSWORKS-496]  Auto service certificate rotation configuration

attributes/default.rb, metadata.rb, recipes/default.rb, templates/default/ca.ini.erb, templates/default/csr-ca.py.erb, templates/default/sql/0.4.2.sql.erb
Dela specific changes
1. configure public(vm forwarded) hopsworks https port and put it in variables tables
2. fix on hopsworks register python scripts
=> HOPSWORKS-498

providers/certs.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-521
=> [HOPSWORKS-521]  Fix ownership of intermediate CRL

metadata.rb, recipes/default.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-519
=> [HOPSWORKS-519]  Refactor Hops RPC TLS attribute

Berksfile, Berksfile.master
JIRA: https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-507?filter=allopenissues
Testing: https://github.com/hopshadoop/hops-testing/pull/75
=> [HOPSWORKS-507] Add shuffle queue property in MapReduce config

templates/default/sql/0.5.0.sql.erb
https://hopshadoop.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-554
=> [HOPSWORKS-554] Add versions of software to the variables table

recipes/install.rb, templates/default/condaexport.sh.erb, templates/default/glassfish_sudoers.erb, templates/default/sql/0.5.0.sql.erb, templates/default/sql/undo/0.5.0__undo.sql.erb
[HOPSWORKS-541] Export/create Anaconda environment from .yml
=> [HOPSWORKS-541] Export/create Anaconda environment from .yml

attributes/default.rb
set hive as the only interpreter
=> HOPSWORKS-198

templates/default/sql/dml/0.6.0.sql.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-596
Depends on https://github.com/logicalclocks/conda-chef/pull/10
=> [HOPSWORKS-596]  Add to variables table provided and preinstalled python library names for conda envs

files/default/sql/ddl/0.6.0.sql, files/default/sql/ddl/undo/0.6.0__undo.sql
Part of Anacodna GC
https://logicalclocks.atlassian.net/browse/HOPSWORKS-648
=> [HOPSWORKS-648]  Changes in DB to support extended system command arguments

Karamelfile, providers/certs.rb, recipes/default.rb, recipes/install.rb, templates/default/dela/register.sh.erb, templates/default/hopssite/hs_dela_certs.sh.erb
[HOPSWORKS-679]  Add the proper python executable
https://logicalclocks.atlassian.net/browse/HOPSWORKS-679
=> [HOPSWORKS-679]  Restructure Conda cookbook

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-800
=> [HOPSWORKS-800]  Fix Hops executor service properties

Berksfile, files/default/sql/ddl/0.6.1.sql, files/default/sql/ddl/undo/0.6.1__undo.sql, templates/default/condaexport.sh.erb, templates/default/jupyter.sh.erb, templates/default/sql/dml/0.6.1.sql.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-811
=> [HOPSWORKS-811] Conda speedup

attributes/default.rb, metadata.rb, templates/default/sql/dml/0.8.1.sql.erb, templates/default/sql/dml/undo/0.8.1__undo.sql.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-890
=> [HOPSWORKS-890]  Add JWT issuer identifier in variables table

templates/default/sql/dml/0.1.0.sql.erb, templates/default/sql/dml/0.4.0.sql.erb
- Move chef attributes for spark dependencies from hops-hadoop to spark-chef
=> [HOPSWORKS-853] Feature Store Tour

attributes/default.rb, files/default/sql/ddl/0.9.0__initial_tables.sql, files/default/sql/ddl/updates/0.9.0.sql, files/default/sql/ddl/updates/undo/0.9.0__undo.sql, metadata.rb, templates/default/sql/dml/0.9.0.sql.erb, templates/default/sql/dml/undo/0.9.0__undo.sql.erb
Reverts logicalclocks/hopsworks-chef#246
=> Revert "[HOPSWORKS-903] Jupyter cleanup and timer bugfixes"

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-919
=> [HOPSWORKS-919]  Create Airflow jdbc connection pool and resource in case of an update

files/default/sql/ddl/updates/0.8.0.sql, files/default/sql/ddl/updates/undo/0.8.0__undo.sql
=> [HOPSWORKS-510] append

templates/default/unzip-hdfs-files.sh.erb, templates/default/zip-hdfs-files.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-945
=> [HOPSWORKS-945]  Copy to HDFS as superuser and chown to the desired user

templates/default/sql/dml/0.10.0.sql.erb, templates/default/sql/dml/undo/0.10.0__undo.sql.erb
Tests: https://github.com/logicalclocks/hops-testing/pull/307
=> [HOPSWORKS-964] Remove tf_spark_connector_version from variables table

files/default/sql/ddl/0.10.0__initial_tables.sql, files/default/sql/ddl/updates/0.10.0.sql, files/default/sql/ddl/updates/undo/0.10.0__undo.sql
https://logicalclocks.atlassian.net/browse/HOPSWORKS-999
=> [HOPSWORKS-999]  Create table for Airflow recovery

Berksfile, recipes/default.rb
=> [HOPSWORKS-875] Add PyTorch, Torchvision and Matplotlib to python base environment

attributes/default.rb, metadata.rb, recipes/install.rb, templates/default/kagent-restart.sh.erb, templates/default/sql/dml/0.10.0.sql.erb, templates/default/sql/dml/undo/0.10.0__undo.sql.erb
Kagent liveness monitor configuration properties
https://logicalclocks.atlassian.net/browse/HOPSWORKS-849
=> [HOPSWORKS-849] kagent liveness monitor

files/default/sql/ddl/0.10.0__initial_tables.sql, files/default/sql/ddl/updates/0.10.0.sql, files/default/sql/ddl/updates/undo/0.10.0__undo.sql
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1068
=> [HOPSWORKS-1068] Change table definition to accommodate recovery for Jupyter JWT service

files/default/sql/ddl/0.10.0__initial_tables.sql, files/default/sql/ddl/updates/0.10.0.sql, files/default/sql/ddl/updates/undo/0.10.0__undo.sql, recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1033
=> [HOPSWORKS-1033] Redesign service JWT renewal protocol

attributes/default.rb, files/default/sql/ddl/0.10.0__initial_tables.sql, files/default/sql/ddl/updates/0.10.0.sql, files/default/sql/ddl/updates/undo/0.10.0__undo.sql, metadata.rb, recipes/default.rb, recipes/install.rb, templates/default/glassfish_sudoers.erb, templates/default/sklearn_flask_server.py.erb, templates/default/sklearn_serving-kill.sh.erb, templates/default/sklearn_serving-launch.sh.erb, templates/default/sklearn_serving.sh.erb, templates/default/sql/dml/0.10.0.sql.erb, templates/default/sql/dml/0.9.0.sql.erb, templates/default/sql/dml/undo/0.10.0__undo.sql.erb
- materialize sklearn scripts to hopsworks bin dir
- rename tfserving table to serving
- rename columns
- add attributes for sklearn serving
=> [HOPSWORKS-751] Add support for sklearn model serving

files/default/sql/ddl/1.0.0__initial_tables.sql, files/default/sql/ddl/updates/1.0.0.sql, files/default/sql/ddl/updates/undo/1.0.0__undo.sql
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1183
=> [HOPSWORKS-1183] Secrets storage tables

files/default/sql/ddl/1.0.0__initial_tables.sql, files/default/sql/ddl/updates/1.0.0.sql, files/default/sql/ddl/updates/undo/1.0.0__undo.sql, templates/default/sql/dml/1.0.0.sql.erb
featurestore:
- drop dependency functionality
- support on-demand feature groups
- custom data connectors
=> [HOPSWORKS-1196]

templates/default/jupyter.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1239
We check if Jupyter server is running from Hopsworks making a REST call to Jupyter's API
=> [HOPSWORKS-1239] Remove ping command

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1247
=> [HOPSWORKS-1247] Deploy protected artifacts when installing Hopsworks EE

files/default/sql/ddl/1.0.0__initial_tables.sql, files/default/sql/ddl/updates/1.0.0.sql, files/default/sql/ddl/updates/undo/1.0.0__undo.sql
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1243
=> [HOPSWORKS-1243] Database changes for Jupyter Git backend

templates/default/sql/dml/1.0.0.sql.erb, templates/default/sql/dml/undo/1.0.0__undo.sql.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1265
=> [HOPSWORKS-1265] Add Hops verification version to variables

templates/default/jupyter-launch.sh.erb, templates/default/jupyter-stop.sh.erb, templates/default/jupyter.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1208
=> [HOPSWORKS-1208] JupyterLab

metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1331
=> [HOPSWORKS-1331] Consistent flag for system upgrades

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1027
https://github.com/logicalclocks/hops-testing/pull/512
=> [HOPSWORKS-1027] Add support for multiple elasticsearch nodes (HA)

files/default/hopsworks_templates/airflow_dag.py, files/default/hopsworks_templates/config_template.json, files/default/hopsworks_templates/jupyter_notebook_config_template.py, files/default/hopsworks_templates/kernel_template.json, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1340
=> [HOPSWORKS-1340] Add airflow dag template

files/default/sql/ddl/1.1.0__initial_tables.sql, files/default/sql/ddl/updates/1.1.0.sql, files/default/sql/ddl/updates/undo/1.1.0__undo.sql
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1380
https://bbc1.sics.se/jenkins/job/HopsWorks-testing/1981/
=> [HOPSWORKS-1380][featurestore] Configure Feature Group statistics during creation

attributes/default.rb, metadata.rb, recipes/default.rb, templates/default/sql/dml/1.1.0.sql.erb, templates/default/sql/dml/undo/1.1.0__undo.sql.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1474
=> [HOPSWORKS-1474] Add reserved project names in the database

recipes/default.rb, recipes/install.rb, templates/default/metrics.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1551
=> [HOPSWORKS-1551] Make Airflow connection pool optional

templates/default/expat-site.xml.erb
should go in only if expat fix also goes in 
https://github.com/logicalclocks/expat/pull/24
=> [HOPSWORKS-1467][append] expat fixes - also affects [HOPSWORKS-1354]

attributes/default.rb, metadata.rb, recipes/default.rb
Fixes could not connect to LDAP error
=> fix ldap conf

Berksfile, recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1617
=> [HOPSWORKS-1617] Resolve host from IP using ohai's fqdn

attributes/default.rb, metadata.rb, templates/default/sql/dml/1.3.0.sql.erb, templates/default/sql/dml/undo/1.3.0__undo.sql.erb
JIRA:
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1409
=> [HOPSWORKS-1409] chef configurable hdfs storage policy

Berksfile, files/default/hopsworks_templates/jupyter_notebook_config_template.py, metadata.rb, recipes/default.rb, templates/default/consul/glassfish-consul.hcl.erb, templates/default/sql/dml/1.3.0.sql.erb, templates/default/sql/dml/undo/1.3.0__undo.sql.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1405
=> [HOPSWORKS-1405] Register Hopsworks with Consul and remove entries from variables table

providers/grants.rb, recipes/default.rb, recipes/hopssite.rb, recipes/install.rb, recipes/migrate.rb, templates/default/expat-site.xml.erb, templates/default/flyway.conf.erb, templates/default/hopssite/hs_env.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1825
=> [HOPSWORKS-1825] Connect to local mysqld

attributes/default.rb, metadata.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1657
=> [HOPSWORKS-1657] System users x.509 v2

attributes/default.rb, metadata.rb, templates/default/dockerImage.sh.erb, templates/default/jupyter.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1914
=> [HOPSWORKS-1914] Common Chef attribute for validation project Docker image name

providers/certs.rb, recipes/install.rb
Further lock down permissions on HopsCA and create new group for accessing Hopsworks users' only certificates
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1904
=> [HOPSWORKS-1904] Create group to access users' only certificates

recipes/default.rb, templates/default/sql/dml/1.4.0.sql.erb, templates/default/sql/dml/undo/1.4.0__undo.sql.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1805
=> [HOPSWORKS-1805] consul for docker registry

attributes/default.rb, metadata.rb, recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1927
=> [HOPSWORKS-1927] Override download URL for Hopsworks EAR for Cloud

metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1927
=> [HOPSWORKS-1927] Remove rogue chars

attributes/default.rb, recipes/default.rb, templates/default/sql/dml/1.4.0.sql.erb, templates/default/sql/dml/undo/1.4.0__undo.sql.erb
Tests: 
https://github.com/logicalclocks/hops-testing-ee/pull/127
=> [HOPSWORKS-1902] Add support for managed docker registries

Berksfile
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1973
=> [HOPSWORKS-1973] Remove master-cloud branch from hopsworks-chef

templates/default/dockerImage.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2013
tests: https://github.com/logicalclocks/hops-testing-ee/pull/168
=> [HOPSWORKS-2013] Cleanup docker images from managed registries

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2042
=> [unmanaged_localhost] Do not deploy Cloud version if it's unmanaged version

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2042
=> Do not deploy Cloud version if it's unmanaged version (#500)

templates/default/sql/dml/2.0.0.sql.erb, templates/default/sql/dml/undo/2.0.0__undo.sql.erb
We need this for integration tests in ruby
=> [HOPSWORKS-2025] Delete job executions

files/default/sql/ddl/1.4.1__initial_tables.sql, files/default/sql/ddl/updates/1.4.1.sql, files/default/sql/ddl/updates/undo/1.4.1__undo.sql
To be merged together with https://github.com/logicalclocks/hopsworks-chef/pull/507
=> Release Hopsworks 1.4.1

templates/default/convert-ipython-notebook.sh.erb
Reverts logicalclocks/hopsworks-chef#490
=> Revert "[HOPSWORKS-1988] IPynb converter fails for notebooks which contain special characters …"

files/default/sql/ddl/2.0.0__initial_tables.sql, files/default/sql/ddl/updates/2.0.0.sql, files/default/sql/ddl/updates/undo/2.0.0__undo.sql
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2084
=> [HOPSWORKS-2084] Remove default_storage option from feature groups

files/default/sql/ddl/2.2.0__initial_tables.sql, files/default/sql/ddl/updates/2.2.0.sql, files/default/sql/ddl/updates/undo/2.2.0__undo.sql
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1978
=> [HOPSWORKS-1978] schematized tags

templates/default/dockerImage.sh.erb
Allows deletion of images inside ACR
=> garbage collection for acr

templates/default/dockerImage.sh.erb
Co-authored-by: Love Walden <>
=> [HOPSWORKS-CLOUD-1527] garbage collection for acr (#570)

templates/default/dockerImage.sh.erb
Reverts logicalclocks/hopsworks-chef#578
=> Revert "[HOPSWORKS-CLOUD-138] append - fix failure to pull images loaded using docker load"

files/default/sql/ddl/updates/2.2.0.sql, files/default/sql/ddl/updates/undo/2.2.0__undo.sql
=> [HOPSWORKS-2404][APPEND] remove metadata designer code

attributes/default.rb, files/default/hopsworks_templates/config_template.json, metadata.rb, templates/default/sql/dml/2.2.0.sql.erb, templates/default/sql/dml/undo/2.2.0__undo.sql.erb
…seconds in the jupyter configuration
=> [HOPSWORKS-2478] make it possible to set livy_session_startup_timeout_seconds in the jupyter configuration

files/default/sql/ddl/updates/2.2.0.sql
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2541
=> [HOPSWORKS-2541] Incorrect column name in sql schema update

attributes/default.rb, metadata.rb, templates/default/sql/dml/2.3.0.sql.erb, templates/default/sql/dml/undo/2.3.0__undo.sql.erb
Resolves https://logicalclocks.atlassian.net/browse/HOPSWORKS-2605
=> [HOPSWORKS-2605] Configuration parameter for Kubernetes client maximum number of attempts

templates/default/global-ca-sign-csr.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2607
=> [HOPSWORKS-2607] Generate x509 with explicit startdate

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2653
=> [HOPSWORKS-2653] Do not unpack flyway if directory already exist

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2653
=> [HOPSWORKS-2653] Do not unpack flyway if directory already exist (#637)

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2659
=> [HOPSWORKS-2659] Fix incorrect guard syntax (#640)

attributes/default.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
=> [HOPSWORKS-2578] Multi-disk nodes

templates/default/expat-site.xml.erb
Fixes logicalclocks/ec2-init#263
=> Create index template and index pattern for services log on upgrade

recipes/default.rb, recipes/image.rb, recipes/master.rb, recipes/slave.rb
Reverts logicalclocks/hopsworks-chef#684
=> Revert "[HOPSWORKS-2808] Fix user home (#683)"

templates/default/expat-site.xml.erb
temporarily disable migration steps
=> [HOPSWORKS-2504][APPEND] feature description

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1867
Fixes https://github.com/logicalclocks/cloud-tickets/issues/25
=> [HOPSWORKS-1867] Change flyway_schema_histroy engine to ndb

recipes/default.rb
Part of https://github.com/logicalclocks/ec2-init/issues/296
=> Add all initial tables sql files to the flyway directory

files/default/sql/ddl/2.5.0__initial_tables.sql, files/default/sql/ddl/updates/2.5.0.sql, files/default/sql/ddl/updates/undo/2.5.0__undo.sql
Add filter tables for training dataset
=> [HOPSWORKS-2855] Add filter tables for training dataset

files/default/sql/ddl/2.5.0__initial_tables.sql, files/default/sql/ddl/2.6.0__initial_tables.sql, files/default/sql/ddl/updates/2.6.0.sql, files/default/sql/ddl/updates/undo/2.6.0__undo.sql
related to https://github.com/logicalclocks/hopsworks-ee/pull/747
=> [HOPSWORKS-2877] Add ModelFeature table

Berksfile, attributes/default.rb, metadata.rb, recipes/install.rb
Devtooling - start glassfish in debug mode
=> [HOPSWORKS-3030] support to start glassfish in debug mode

templates/default/sql/dml/2.2.0.sql.erb
kfserving renamed to kserve. Only renaming chef variable name, not hopsworks variable.
=>  [HOPSWORKS-2979] Append

attributes/default.rb, metadata.rb, templates/default/sql/dml/2.6.0.sql.erb, templates/default/sql/dml/undo/2.6.0__undo.sql.erb
[HOPSWORKS-3120] Quotas for total number of model deployments
https://hopsworks.atlassian.net/browse/HOPSWORKS-3120
[HOPSWORKS-3120]: https://hopsworks.atlassian.net/browse/HOPSWORKS-3120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [HOPSWORKS-3120] Attributes to configure quotas

attributes/default.rb
Resolves https://hopsworks.atlassian.net/browse/HOPSWORKS-3333
=> [HOPSWORKS-3333] Increase application certificate validity period

templates/default/sql/dml/3.0.0.sql.erb
https://hopsworks.atlassian.net/browse/HWORKS-94
=> [HWORKS-94] Use REPLACE instead of INSERT in DML files

providers/certs.rb
Fixes https://hopsworks.atlassian.net/browse/HWORKS-116
=> [HWORKS-116] Convert port to Integer

recipes/default.rb
Fixes https://hopsworks.atlassian.net/browse/HWORKS-115
=> [HWORKS-115] Skip Kubernetes CA configuration if we are using managed Kubernetes

recipes/default.rb
https://hopsworks.atlassian.net/browse/HOPSWORKS-3116
=> [HOPSWORKS-3116] Flyway should ignore patch version number

files/default/sql/ddl/updates/3.1.0.sql, files/default/sql/ddl/updates/undo/3.1.0__undo.sql
s. https://hopsworks.atlassian.net/browse/FSTORE-359
=> [FSTORE-359] Rename Transformation Function Output Types

templates/default/dockerImage.sh.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-112
=> [CLOUD-112] fix image deleting on azure

recipes/default.rb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-165
=> [CLOUD-165] do not set ear url for cloud in chef

attributes/default.rb, metadata.rb, providers/certs.rb
Resolves https://hopsworks.atlassian.net/browse/HWORKS-256
=> [HWORKS-256] Optional configuration option to deploy intermediate CA certificate to Glassfish

templates/default/dockerImage.sh.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-132
=> [CLOUD-132] support for online backup in the cloud

files/default/sql/ddl/3.1.0__initial_tables.sql, files/default/sql/ddl/updates/3.1.0.sql, files/default/sql/ddl/updates/undo/3.1.0__undo.sql
Don't merge before FSTORE-441 merge in the backend
=> [FSTORE-442] Increase kwargs size in expectation table

recipes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-301
=> [HWORKS-301] Append hopsworks.ldap.basedn property to LDAP resource

attributes/default.rb, metadata.rb, recipes/default.rb, recipes/install.rb, templates/default/metrics.xml.erb
https://hopsworks.atlassian.net/browse/HWORKS-210
=> [HWORKS-210] jupyter threads fill up executor pool

attributes/default.rb, recipes/default.rb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-211
=> [CLOUD-211] move staging dir to data volume

attributes/default.rb, metadata.rb, templates/default/sql/dml/3.0.0.sql.erb, templates/default/sql/dml/undo/3.0.0__undo.sql.erb
https://hopsworks.atlassian.net/browse/HWORKS-340
=> [HWORKS-340] Expose attribute to explicitly enable/disable LDAP group sync thread

Karamelfile
https://hopsworks.atlassian.net/browse/CLOUD-365
=> [CLOUD-365] Ad dependency to ndb::restore_sql recipe

templates/default/docker-cgroup-rewrite.sh.erb
https://hopsworks.atlassian.net/browse/CLOUD-430
=> [CLOUD-430] Adapt to cgroup2

Karamelfile, files/default/sql/ddl/updates/3.1.0.sql, recipes/default.rb
This reverts commit a210ebc92d9093cfea87b97f406ced8835bbad39.
=> Prepare for 3.1.1 release

templates/default/dockerImage.sh.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-552
=> [CLOUD-552] Explicity add /usr/local/bin to PATH

templates/default/docker-cgroup-rewrite.sh.erb, templates/default/sql/dml/3.2.0.sql.erb
* Add variable for docker cgroup parent
* Undo
=> [HWORKS-512] Add variable for docker cgroup parent (#926)

recipes/default.rb, templates/default/sql/dml/3.2.0.sql.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-563
=> [CLOUD-563] Move grants to DML

recipes/default.rb, templates/default/sql/dml/3.2.0.sql.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-563
=> [CLOUD-563] Move grants to DML (#940)

recipes/default.rb
https://hopsworks.atlassian.net/browse/CLOUD-606
=> [CLOUD-606] Mysql username configuration

attributes/default.rb, templates/default/sql/dml/3.3.0.sql.erb
necessary as otherwise user wouldn't be able to update connector
=> [FSTORE-840] Use existing Kafka cluster

files/default/sql/ddl/updates/3.3.0.sql, templates/default/sql/dml/3.0.0.sql.erb
Fixes https://hopsworks.atlassian.net/browse/FSTORE-857
=> [FSTORE-857] Overwrite hsfs_utils in jobs when upgrading to 3.3.0

providers/certs.rb
Fixes https://hopsworks.atlassian.net/browse/HWORKS-663
=> [HWORKS-663] Fix condition for remote_file/intermediate_ca_url

attributes/default.rb, files/default/sql/ddl/3.4.0__initial_tables.sql, files/default/sql/ddl/updates/3.4.0.sql, metadata.rb, recipes/default.rb, recipes/install.rb, templates/default/sql/dml/0.1.0.sql.erb, templates/default/sql/dml/3.4.0.sql.erb
=> [HWORKS-704][HWORKS-705][HWORKS-354]

attributes/default.rb, metadata.rb, templates/default/sql/dml/3.4.0.sql.erb
https://hopsworks.atlassian.net/browse/HWORKS-735
=> [HWORKS-735] Expose attribute for configuring ldap search group filter

attributes/default.rb, metadata.rb, recipes/judge.rb, templates/default/judge/default.conf.erb, templates/default/judge/judge.service.erb
https://hopsworks.atlassian.net/browse/HWORKS-738
=> [HWORKS-738] Provision Judge service

files/default/sql/ddl/3.4.0__initial_tables.sql, files/default/sql/ddl/updates/3.4.0.sql
Reverts logicalclocks/hopsworks-chef#1043
=> Revert "[FSTORE-1020] Modify training_dataset_filter_condition constraint"

templates/default/sql/dml/3.4.0.sql.erb
https://hopsworks.atlassian.net/browse/HWORKS-816
=> [HWORKS-816] Insert multiregion configuration in Hopsworks settings

templates/default/judge/judge.service.erb
https://hopsworks.atlassian.net/browse/HWORKS-815
=> [HWORKS-815] Remove requires directive so judge service will not be stopped when stopping docker. Instead it will be killed and restarted

templates/default/dockerImage.sh.erb
[HWORKS-826] Remove old code
[HWORKS-826]: https://hopsworks.atlassian.net/browse/HWORKS-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [HWORKS-826] Docker build should push to both region registries (#1069)

Berksfile, templates/default/dockerImage.sh.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-97
=> [CLOUD-97] Add support for GCR/GKE

templates/default/systemd.service.erb
https://hopsworks.atlassian.net/browse/HWORKS-946
=> [HWORKS-946] Extra After systemd units

files/default/sql/ddl/3.7.0__initial_tables.sql, files/default/sql/ddl/updates/3.7.0.sql
Reverts logicalclocks/hopsworks-chef#1101
=> Revert "[FSTORE-1190] Attach model to embedding feature"

recipes/migrate.rb
https://hopsworks.atlassian.net/browse/HWORKS-992
=> [HWORKS-992] Do not use renewal tokens anylonger

Karamelfile
https://hopsworks.atlassian.net/browse/HWORKS-1058
=> [HWORKS-1058] Migrate should run after default recipe

files/default/sql/ddl/updates/3.7.0.sql
Fixes https://hopsworks.atlassian.net/browse/HWORKS-1084
=> [HWORKS-1084] Handle migration statements in batches for large tables

providers/configure_server.rb, recipes/config_node.rb, recipes/default.rb, resources/configure_server.rb
https://hopsworks.atlassian.net/browse/HWORKS-1059
=> [HWORKS-1059] Move API key generation in config_node if deploying HA configuration

providers/configure_server.rb, recipes/default.rb, resources/configure_server.rb
https://hopsworks.atlassian.net/browse/HWORKS-1059
=> [HWORKS-1059] Retry generating internal API key when Glassfish is unavailable

files/default/hopsworks_templates/custom_docker_commands_template
=> [HWORKS-1039] Any command with non-zero exit in the custom commands script should fail the docker build

providers/configure_server.rb, recipes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-1246
=> [HWORKS-1246] Close all JDBC connections and reconnect in case of a failure

attributes/default.rb, metadata.rb, templates/default/sql/dml/3.8.0.sql.erb
https://hopsworks.atlassian.net/browse/HWORKS-1284
=> [HWORKS-1284] Add configuration property to disable FixReceivers timer
