- recipes/default.rb
- recipes/install.rb
- templates/default/app.log4j.properties.erb
- templates/default/log4j.properties.erb
add a log4j.properties for the log written by dependencies  such as zookeeper. This should allow us to have less noise in the glassfish logs.
> add a log4j.properties for the log written by hopsworks dependencies

- recipes/install.rb
- templates/default/glassfish_sudoers.erb
- templates/default/ndb_backup.sh.erb
- templates/default/tables.sql.erb
A new ndb_backups table was added for storing backup_ids and dates.
A new ndb_backup.sh script was added to start/remove a backup. This script needed sudo privileges to change to the 'mysql' user to run it. The script was added to sudoers.d/glassfish to enable this.
> Ndb backups

- recipes/install.rb
Add Hopsworks user to Hops group in order to be able to create $ZEPPELIN_HOME/Projects directory
> Add Hopsworks user to Hops group

- Berksfile
- recipes/default.rb
- recipes/install.rb
Fixes to build from source for tensorflow including switches for Intel MKL, RDMA, and MPI.
GPU cannot be built from source for centos yet - works for ubuntu.
> Build from source with mkl/rdma/mpi support and Centos fixes

- templates/default/views.sql.erb
change name of column in projects_last_payment view to avoid confusion with mysql max syntax
> [HOPSWORKS-181] 

- recipes/default.rb
- recipes/install.rb
* Add hopsworks and jupyter user to certificates group and remove acl
* Change hops-hadoop-chef repo for testing
* Create transient certificates directory in Chef with correct permissions
* Add forgotten append property to group resource
* Put back upstream hops-hadoop-chef repo
https://hopshadoop.atlassian.net/browse/HOPSWORKS-232
> HOPSWORKS-232

- templates/default/tables.sql.erb
I renamed the key fields as the orm didn't like it. I forgot to change them in the previous PR.
> [HOPSWORKS-307] Fix fields name in projectgenericuser_certs

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- recipes/install.rb
- templates/default/dump_web_logs_to_hdfs.sh.erb
[HOPSWORKS-381]  Source hdfs web logs dumper. Missing the remote directory and add it as a cron job
[HOPSWORKS-381]  Enable http logging
[HOPSWORKS-381]  Add cron job to dump log files to hdfs
[HOPSWORKS-381]  Put dummy remote path. I should fix this, just for testing
[HOPSWORKS-381]  Fix name of script in cron job
[HOPSWORKS-381]  Change remote weblogs dir
[HOPSWORKS-381]  Change to testing branches
[HOPSWORKS-381]  Run cron every hour for testing
[HOPSWORKS-381]  Fix in dumper script and consider a non systemd system
[HOPSWORKS-381]  Put back master branches and run cron job daily
https://hopshadoop.atlassian.net/browse/HOPSWORKS-381
> [HOPSWORKS-381]  Log HTTP requests and dump them to HDFS periodically

- templates/default/jupyter-launch.sh.erb
- templates/default/jupyter.sh.erb
Add the token to be used by Jupyter as an argument to allow it to be explicitly set instead of reading it from log files.
This is part of a larger Hopsworks refactoring and needs to be shipped together.
> [HOPSWORKS-1163] Allow explicit setting of the Jupyter token

- attributes/default.rb
- recipes/default.rb
- recipes/install.rb
[HOPSWORKS-1357] flyway_schema_history fix for versions < 0.6 doesn't work after 1.0.0
[HOPSWORKS-1358] Handle glassfish upgrade from 4.1.2.174 to 4.1.2.181
[HOPSWORKS-1357]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-1357
[HOPSWORKS-1358]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-1358
> [HOPSWORKS-1357][HOPSWORKS-1358]

- recipes/default.rb
[HOPSWORKS-1395] Remove notify resource to create symlink
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1395
[HOPSWORKS-1395]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-1395
> [HOPSWORKS-1395] Remove symlink to intermediate CA CRL

- files/default/sql/ddl/1.3.0__initial_tables.sql
- files/default/sql/ddl/updates/1.3.0.sql
- files/default/sql/ddl/updates/undo/1.3.0__undo.sql
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1678
https://bbc1.sics.se/jenkins/job/Hopsworks-testing-ee/189/
> [HOPSWORKS-1678] Extend training dataset endpoint to save train-test split information as metadata

- files/default/sql/ddl/1.4.0__initial_tables.sql
- files/default/sql/ddl/updates/1.4.0.sql
- files/default/sql/ddl/updates/undo/1.4.0__undo.sql
The changes for feature_store_s3_connector are for issue HOPSWORKS-1592
> [HOPSWORKS-1929] enforce unique names in training dataset splits

- templates/default/sql/dml/2.0.0.sql.erb
- templates/default/sql/dml/undo/2.0.0__undo.sql.erb
https://logicalclocks.atlassian.net/jira/software/c/projects/HOPSWORKS/issues/HOPSWORKS-1918
> [HOPSWORKS-1918] Spark executor memory not modifiable from UI when starting jupyter fix

- files/default/sql/ddl/2.1.0__initial_tables.sql
- files/default/sql/ddl/updates/2.1.0.sql
- files/default/sql/ddl/updates/undo/2.1.0__undo.sql
There is one issue @SirOibaf the following columns should have been removed in the 2.0 release. Probably a bad refactor. they don't hurt in the table, however, I add drop column statements for them in the 2.1.0 update sql, which will fail if they exist. I am wondering if we should just leave them for 2.0 clusters or fix the release branch etc?
```
`cluster_analysis_enabled` TINYINT(1) NOT NULL DEFAULT '1',
`num_clusters` int(11) NOT NULL DEFAULT '5',
`num_bins` INT(11) NOT NULL DEFAULT '20',
`corr_method` VARCHAR(50) NOT NULL DEFAULT 'pearson',
```
> [HOPSWORKS-2280] Save statistics configuration also for training datasets

- templates/default/sql/dml/0.1.0.sql.erb
- templates/default/sql/dml/3.0.0.sql.erb
The auditor role is not used anymore and should be removed.
> [HOPSWORKS-2723] Remove AUDITOR role

- attributes/default.rb
- recipes/install.rb
- templates/default/unzip-hdfs-files.sh.erb
* dtrx not available on ubuntu 20.04
* add tensorflow dependency
* Move dtrx installation as part of hops-system
* More fixes for centos8
* Revert Berksfile changes
> [HOPSWORKS-2647] Support Ubuntu 20.04 / Centos 8 (#679)

- files/default/sql/ddl/updates/3.1.0.sql
- recipes/default.rb
[HWORKS-456] Disable validation of sql ddl files during migration
[HWORKS-456]: https://hopsworks.atlassian.net/browse/HWORKS-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HWORKS-456] Re-organize ddl statements

- attributes/default.rb
- metadata.rb
- recipes/default.rb
- templates/default/sql/dml/3.3.0.sql.erb
[CLOUD-445] Change subject of glassfish internal certificate to accomodate multiple instances
[CLOUD-445] Configuration for extra SAN for users
[CLOUD-445] Parse json instead of just string
[CLOUD-445]: https://hopsworks.atlassian.net/browse/CLOUD-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLOUD-445]: https://hopsworks.atlassian.net/browse/CLOUD-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLOUD-445]: https://hopsworks.atlassian.net/browse/CLOUD-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CLOUD-445] Hopsworks configuration parameter with unix usernames

- files/default/sql/ddl/3.3.0__initial_tables.sql
- files/default/sql/ddl/updates/3.3.0.sql
foreign key of `stream_feature_group_id` is missing in the talble `cached_feature_extra_constraints`
> [FSTORE-709] add stream fg key to cached_feature_extra_constraints

- Karamelfile
* [HWORKS-1058] Migrate should run after default recipe
* [HWORKS-1058] Move migrate after DAS and Config node
[HWORKS-1058]: https://hopsworks.atlassian.net/browse/HWORKS-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HWORKS-1058]: https://hopsworks.atlassian.net/browse/HWORKS-1058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [HWORKS-1058] Migrate should run after default recipe
